### ISSUE TITLE
Could you change license to a permissive license type?

### ISSUE THREAD

**Issue by prepare** [cambiata/NanoVGDotNet#2]
the current license is lgpl3

could you change the license to a permissive license  type?

reason: this will be good when the source code is merge with other projects

 :)

**Comment by prepare** [comment]
Ping @cambiata

**Comment by codeyash** [comment]
He is not author and can't change license. He only mirror it in github.

Original author's site 
https://sites.google.com/site/bitiopia/

Contact him. 

License is problem I agree.

**Comment by prepare** [comment]
Thank you :)
